basePath: /
definitions:
  apimodel.RoleCreate:
    properties:
      name:
        type: string
      permission:
        items:
          type: string
        type: array
    type: object
  apimodel.RoleUpdate:
    properties:
      name:
        type: string
      permission:
        items:
          type: string
        type: array
    type: object
  apimodel.StaffCreate:
    properties:
      avatar:
        type: string
      email:
        type: string
      name:
        type: string
      phone:
        type: string
      role:
        type: string
    type: object
  apimodel.StaffLoginWithEmail:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  apimodel.StaffUpdate:
    properties:
      avatar:
        type: string
      email:
        type: string
      name:
        type: string
      phone:
        type: string
      role:
        type: string
    type: object
  constant.Permission:
    properties:
      code:
        type: string
      name:
        type: string
    type: object
  ptime.TimeResponse:
    properties:
      time:
        type: string
    type: object
  responsemodel.ResponseCreate:
    properties:
      id:
        type: string
    type: object
  responsemodel.ResponseList:
    properties:
      limit:
        type: integer
      list: {}
      total:
        type: integer
    type: object
  responsemodel.ResponseUpdate:
    properties:
      id:
        type: string
    type: object
  responsemodel.Role:
    properties:
      code:
        type: string
      createdAt:
        $ref: '#/definitions/ptime.TimeResponse'
      id:
        type: string
      name:
        type: string
      permissions:
        items:
          $ref: '#/definitions/constant.Permission'
        type: array
      updatedAt:
        $ref: '#/definitions/ptime.TimeResponse'
    type: object
  responsemodel.RoleDetail:
    properties:
      role:
        $ref: '#/definitions/responsemodel.Role'
    type: object
  responsemodel.RoleShort:
    properties:
      _id:
        type: string
      isAdmin:
        type: boolean
      name:
        type: string
    type: object
  responsemodel.Staff:
    properties:
      _id:
        type: string
      active:
        type: boolean
      avatar:
        type: string
      createdAt:
        type: string
      email:
        type: string
      isRoot:
        type: boolean
      name:
        type: string
      phone:
        type: string
      role:
        $ref: '#/definitions/responsemodel.RoleShort'
      updatedAt:
        type: string
    type: object
  responsemodel.StaffLogin:
    properties:
      _id:
        type: string
      token:
        type: string
    type: object
info:
  contact:
    email: dev@cashbag.vn
    name: Dev team
    url: https://selly.vn
  description: API for admin management.
  termsOfService: https://selly.vn
  title: Admin API
  version: "1.0"
paths:
  /roles:
    get:
      consumes:
      - application/json
      operationId: role-all
      parameters:
      - in: query
        name: keyword
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.ResponseList'
      security:
      - ApikeyAuth: []
      summary: ALl
      tags:
      - Role
    post:
      consumes:
      - application/json
      operationId: role-create
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/apimodel.RoleCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.ResponseCreate'
      security:
      - ApiKeyAuth: []
      summary: Create
      tags:
      - Role
  /roles/{id}:
    delete:
      consumes:
      - application/json
      operationId: role-delete-one
      parameters:
      - description: role id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: ""
      security:
      - ApiKeyAuth: []
      summary: DeleteOne
      tags:
      - Role
    get:
      consumes:
      - application/json
      operationId: role-detail
      parameters:
      - description: role id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.RoleDetail'
      security:
      - ApiKeyAuth: []
      summary: Detail
      tags:
      - Role
    put:
      consumes:
      - application/json
      operationId: role-update
      parameters:
      - description: role id
        in: path
        name: id
        required: true
        type: string
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/apimodel.RoleUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.ResponseUpdate'
      security:
      - ApiKeyAuth: []
      summary: Update
      tags:
      - Role
  /staff:
    get:
      consumes:
      - application/json
      operationId: staff-all
      parameters:
      - in: query
        name: active
        type: string
      - in: query
        name: keyword
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.ResponseList'
      security:
      - ApiKeyAuth: []
      summary: All
      tags:
      - Staff
  /staff/{id}/change-status:
    patch:
      consumes:
      - application/json
      operationId: change-status
      parameters:
      - description: staff id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.ResponseUpdate'
      security:
      - ApiKeyAuth: []
      summary: ChangeStatus
      tags:
      - Staff
  /staffs:
    post:
      consumes:
      - application/json
      operationId: staff-create
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/apimodel.StaffCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.ResponseCreate'
      security:
      - ApikeyAuth: []
      summary: Create
      tags:
      - Staff
  /staffs/{id}:
    put:
      consumes:
      - application/json
      operationId: update-staff
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/apimodel.StaffUpdate'
      - description: staff id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.ResponseUpdate'
      security:
      - ApiKeyAuth: []
      summary: Update
      tags:
      - Staff
  /staffs/login-with-email:
    post:
      consumes:
      - application/json
      operationId: login-with-email
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/apimodel.StaffLoginWithEmail'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.StaffLogin'
      security:
      - ApiKeyAuth: []
      summary: LoginWithEmail
      tags:
      - Staff
  /staffs/me:
    get:
      consumes:
      - application/json
      operationId: get-me
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.Staff'
      security:
      - ApiKeyAuth: []
      summary: GetMe
      tags:
      - Staff
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
